### ISSUE TITLE
mc alias conflicts with midnight commander

### ISSUE THREAD

**Issue by hy37id** [gusaiani/elixir-oh-my-zsh#4]
midnight commander is commonly used on many linux distros (mc), so I think that alias mc should be changed to different one to avoid name conflicts

**Comment by gusaiani** [comment]
Thank you very much for pointing this out, @hy37id.

I'll be on the lookout for more users who prefer to forfeit `mc` to midnight commander.
If the number is significant, I will consider changing the alias.

I should point out that it's fairly easy to bypass any alias just by deleting its line, in this case: https://github.com/gusaiani/elixir-oh-my-zsh/blob/master/elixir.plugin.zsh#L8

I encourage everyone to take this file and make them as personal as possible for themselves.

Cheers!
