### ISSUE TITLE
Using mix phoenix.command is deprecated in favor of mix phx.cmd in 1.3rc

### ISSUE THREAD

**Issue by agustif** [gusaiani/elixir-oh-my-zsh#5]
The old command does resolve to the expanded version, so I'm wondering if it's best for now to just leave it as it is, or maybe have some logic detecting your versions... 

I dont know. 

Thanks for the package!!

**Comment by gusaiani** [comment]
Thanks for mentioning this and for using the package, @agustif.

I'm inclined to leaving it as is for the moment, but will look into the roadmap for the discontinuation of `mix phoenix`.

I haven't been using Phoenix very much lately, so please feel free to keep me posted.

Cheers!

**Comment by agustif** [comment]
Thanks, yeah it's a non-issue for now. 

It has saved me incountable keystrokes!
